### ISSUE TITLE
BUG: OCR of some scanned PDF documents is not working

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#2810] opened 2023-01-13 16:52 UTC
**Describe the bug**
OCR does not seem to be working on some PDF documents

**To Reproduce**
1. Go to https://aleph.occrp.org/entities/106973902.e02724a39ee4b5cafb3b93e1f153d698f60b83bc
2. View the document
3. Click the text tab
4. Observe that the text is not present

**Expected behavior**
The text for the document should be visible in the text tab

**Aleph version**
3.13.1-rc4

**Comment by stchris** [comment] 2023-01-16 07:29
I'm doing some tests with the provided pdf but I'm not entirely sure if this is a regression. It looks like an issue with TIFF files in PDFs (which we usually convert back to PDF to OCR 🙈 ).

**Comment by Rosencrantz** [comment] 2023-01-16 09:49
Yeah, I would agree with that assessment. I think though, it would be good to address this issue (if possible) given that our collective heads seem to be in this space right now.

Do you think that this issue should block me performing an Aleph release to the community this week?

**Comment by stchris** [comment] 2023-01-16 10:32
I will get back to you on this being a regression or not. I think that should be our deciding factor. Do you think that's fair?

**Comment by Rosencrantz** [comment] 2023-01-16 10:44
I do think that is fair. It's a good way to approach this.

**Comment by Rosencrantz** [comment] 2023-01-16 11:51
Well, interesting. Glad we managed to pick this up. I'll hold off on a new release for now.

**Comment by stchris** [comment] 2023-01-16 13:52
One way of fixing it is to convert .tiff to .png and then OCR that, but that seems to incur a significant performance penalty so I'm looking at ways of limiting that.

**Comment by stchris** [comment] 2023-01-18 11:46
Fixed in ingest-file, released with `3.13.1`.

**Closed by stchris** 2023-01-18 11:46 UTC
Labels: bug
