### ISSUE TITLE
BUG: Alerts only alert on the first word and not on the full words.

### ISSUE THREAD

**Issue by DrWhax** [alephdata/aleph#3001] opened 2023-04-19 10:38 UTC
**Describe the bug**

I've setup multiple alerts in Aleph, however it only alerts on parts of the word you've setup an alert for.

Example: Alert for: fox-it.

But the alerts I get are only for: fox

**To Reproduce**
1. Go to 'Alerts'
2. Click on 'Create a new tracking alert'
3. Wait to get a tracking alert
4. See it only being alerted for part of the word.

**Expected behavior**
I should get an alert for fox-it not for fox.

**Aleph version**
Running on aleph.occrp.org

**Screenshots**

**Additional context**

**Comment by tillprochaska** [comment] 2023-04-19 10:56
I think this is actually the intended behavior, but maybe the UX around this can be improved.

An alert is triggered whenever there are new results for the given search query. In Aleph, when you have multi-term search queries, entities that contain any of the terms are considered matches (entities that contain all terms obviously rank higher).

If you’re interested in matches that contain all terms in the exact order, you can enclose the query in double quotes: `"fox-it"`.

Even then, the alert may still be triggered by results with slightly different spelling like though. For example, `fox it` without a dash would be considered a match. However, entities that contain only `fox` or documents that contain the terms in a different order won’t trigger the alert.

**Comment by tillprochaska** [comment] 2023-04-19 11:02
Never mind, what I wrote above likely isn’t correct. Another reason why this might happen in this particular case might be `it` being filtered out as a stop word. @DrWhax Did you run into this issue for this particular query/alert only, or did you observe similar behavior for other queries/alerts.

**Comment by DrWhax** [comment] 2023-04-25 15:32
Yes, it also happens for:

- Q Cyber
- NSO Group

**Comment by DrWhax** [comment] 2023-04-25 15:33
Without the quotes of course.

**Comment by Rosencrantz** [comment] 2023-05-02 13:40
We should verify that this problem is what we think it is, and then (if it is) perhaps look at updating our documentation to reflect the way in which things work.

**Comment by tillprochaska** [comment] 2023-05-04 11:04
This is a summary of what I’ve found out (or rather not found out) so far…

As far as I can see, we don’t use any stop word filters in our setup, so "it" being filtered out as a stop word shouldn’t be the reason for the behavior you’re seeing.

We also default to a logical `AND` in case a search query doesn’t explicitly specify an operator, i.e. `NSO Group` should become `NSO AND Group`. Consequently `NSO Group` should match only entities that contain both terms.

And this actually seems to work as intended. I created a test investigation with three company entities: "NSO Group", "NSO Inc.", "ACME Group". Searching for "NSO Group" returns only the first entitiy.

So I took a closer look at the ES queries we generated when a) executing a normal search via the UI and b) checking whether there are any new entities matching an alert.

<details>
<summary>Search query</summary>

```json
{
  "bool": {
    "should": [
      {
        "query_string": {
          "query": "NSO Group",
          "lenient": true,
          "fields": [
            "fingerprints.text^3",
            "text"
          ],
          "default_operator": "AND",
          "minimum_should_match": "66%"
        }
      }
    ],
    "must": [],
    "must_not": [],
    "filter": [
      {
        "terms": {
          "collection_id": [
            64,
            63
          ]
        }
      }
    ],
    "minimum_should_match": 1
  }
}
```
</details>
<details>
<summary>Alert query</summary>

```json
{
  "bool": {
    "should": [
      {
        "query_string": {
          "query": "NSO Group",
          "lenient": true,
          "fields": [
            "text"
          ],
          "default_operator": "AND",
          "minimum_should_match": "66%"
        }
      }
    ],
    "filter": [
      {
        "terms": {
          "collection_id": [
            64,
            63
          ]
        }
      },
      {
        "range": {
          "updated_at": {
            "gt": "2023-05-04T10:49:20.124050"
          }
        }
      }
    ],
    "minimum_should_match": 1
  }
}
```
</details>

These two queries look pretty similar and should return the same results. And looking at the logs, I can actually see that my alert for "NSO Group" matched only the "NSO Group" company entity, and none of the others.

**Comment by DrWhax** [comment] 2023-05-04 13:28
Hey Till,

Attaching some more results I get:

![Screenshot 2023-05-04 at 14 24 39](https://user-images.githubusercontent.com/299879/236218260-5b0e1a5c-8e23-4fbe-a106-a195d391c161.png)

That is for fox-it.

![Screenshot 2023-05-04 at 14 24 45](https://user-images.githubusercontent.com/299879/236218398-78f4487c-b686-4071-aa13-2e827ee97663.png)

That is for both Q Cyber and NSO Group.

![Screenshot 2023-05-04 at 14 25 00](https://user-images.githubusercontent.com/299879/236218489-fb16f2f7-4f4f-4476-ad40-e47c6d103b02.png)

I also sometimes get back empty results? :)

I'm not sure if this is the correct space either. But in the homepage dashboard where new alerts are displayed, it would be great if when you click the link, you'll get linked to the right place where this alert originates from.

**Comment by tillprochaska** [comment] 2023-05-05 09:26
Thanks @DrWhax for providing additional examples/context. I was able to confirm that the documents you have been alerted about do indeed contain both terms ("NSO" and "Group" / "Fox" and "it"), although not necessarily on the same page. That means that this is actually the intended behavior in this case and I will close this issue.

If you want to receive only alerts for documents that contain the phrase "NSO Group", enclose the query in quotes (`"NSO Group"`). 

Probably not helpful in this particular case, but you can also use a proximity search (`"NSO Group"~2`) which will only match documents that contain both terms with at most two other terms in between ("NSO lorem ipsum Group" would match, but "NSO lorem ipsum dolor sit amet Group" wouldn’t).

There are however a couple of related/follow-up enhancements that we could implement. I will create separate issues for them:

* Consider whether we can user better wording in the UI and in the new user guide to make people aware that their alert will match documents that contain search terms in any position and possibly suggest phrase searches.
* When searching within a document that contains search terms on different pages (e.g. "NSO" on the first page and "Group" on the second page) Aleph finds no matches. This is because we default to `AND` operators. We could consider loosening this and defaulting to `OR` for searches within documents.

Thanks again for raising this issue and providing reproduction steps! Thanks also for mentioning that you’re seeing weird notifications for empty results. This is likely related to #2114 (notifications are not deleted when a dataset is deleted).

**Closed by tillprochaska** 2023-05-05 09:26 UTC
Labels: bug, Moderate
