### ISSUE TITLE
FEATURE: Customizable landing/index page

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#2496] opened 2022-09-03 11:50 UTC
**Is your feature request related to a problem? Please describe.**

When someone lands on our page, it is mostly indistinguishable (apart from the small change in the nav bar) from the OCCRP flagship instance. In particular:

- The title on the hero still just says `Aleph`
- The search suggestions are misleading and imply someone might want to search for Putin or TeliaSonera which may or may not be searchable in our (or anyone else's) data sets

![Screenshot 2022-09-03 at 13-43-38 Find public records and leaks - Hunter](https://user-images.githubusercontent.com/59644018/188269136-caf543b4-1aed-4f7a-a908-eba97e316c8c.png)

**Describe the solution you'd like**

- The name `Aleph` in the hero should be pulled from the same env var that sets the name in the nav bar
- The search bar should have generic text like "What do you want to investigate?" or "What are you looking for?"
- It should be possible to set an env var to an HTML snippet that is loaded somewhere in the hero (after the text "Search docs, companies, and people" or after the counts of entities/data etc). This would allow the admin to introduce their instance like "This is the database for so-and-so run by such-and-such and it contains blah blah blah."

**Describe alternatives you've considered**

- A fully customizable index page is probably incompatible with the jinja templates and other things and would create maintenance burden. Probably not a good idea.

**Comment by tillprochaska** [comment] 2022-09-03 12:05
You should already be able to customize most of the contents on the home page (and create other pages as well!) using markdown files with YAML frontmatter. It’s poorly documented at the moment, but you should be able to figure out which contents you can change by looking at the [default contents](https://github.com/alephdata/aleph/blob/main/aleph/pages/home.en.md).

You can configure the directory that contains the markdown files using the `ALEPH_PAGES_PATH` environment variable.

**Comment by glenn-sorrentino** [comment] 2022-09-03 19:47
Not final by any means, but here's an interface we've been exploring: 
![Group 16](https://user-images.githubusercontent.com/28545431/188285750-085c21f2-aaa1-4ee8-956d-1b9cfcd69be9.png)

I may repeat some of what @brassy-endomorph said, but to call out the features here:

1. Custom branding
2. Customizable search placeholder text
3. Quick filters that can be dynamically generated based on the dataset.
4. Proactive content - rather than only showing informational text below the fold, can we surface groups of data? These can be generated using a fixed set, showing popular queries, automatically based on time (new today, this month, etc).

**Comment by tillprochaska** [comment] 2022-09-09 11:45
> I think we might just have to settle with a bit more customization on the index page like @tillprochaska suggested. I'm going to try futzing around with this and see if I can get a bit more of what we want using just the markdown templates.

Yes, that sounds like a good way forward. Unfortunately, providing full theming support isn’t feasible at the moment given the limited resources of our team and also the constraints of the libraries we’re using.

I’m going to close this issue for now, but please feel free to reopen in case you find contents that you’d like to customize but currently cannot customize using the Markdown files.

**Closed by tillprochaska** 2022-09-09 11:45 UTC
Labels: feature-request, triage

**Comment by brassy-endomorph** [comment] 2022-10-16 16:04
@tillprochaska  This doesn't seem to work at all as when I mount a single changed markdown file into the API container at the default path, the changes are not visible. The file is definitely there in the container, and it's mounted before the application starts, so there shouldn't be any race condition.

**Comment by brassy-endomorph** [comment] 2022-10-16 16:07
Specifically, the page `/aleph/site/aleph.occrp.org/pages/home.en.md` doesn't work

**Comment by tillprochaska** [comment] 2022-10-16 18:47
Hi @brassy-endomorph, unfortunately, I wasn’t able to reproduce this (and we’re actually using this for OCCRP’s Aleph instance at aleph.occrp.org).

Here’s what works for me:

1. Create a new directory `/site/my-aleph/pages`.

3. Create a new YAML file at `site/my-aleph/pages/lorem-ipsum.en.yml`:
   
   ```yml
   ---
   title: Lorem Ipsum
   short: Lorem Ipsum
   menu: true
   ---
   
   Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. 

   ```

4. Create a new YAML file at `site/my-aleph/pages/home.en.yml`:
   ```yml
   ---
   home: true
   title: 'My Aleph'
   description: 'My custom slogan'
   samples: ["Lorem ipsum"]
   ---
   ```

5. Set the `ALEPH_PAGES_PATH` env variable to `/aleph/site/my-aleph/pages`.

7. Restart the `api` service.

I can now see the custom contents on the home page as well as a custom page named "Lorem Ipsum" in the nav bar:

<img width="670" alt="Screen Shot 2022-10-16 at 20 45 11" src="https://user-images.githubusercontent.com/1512805/196052489-29f8753e-e37a-49aa-9298-1a3a2be84c66.png">

<img width="1020" alt="Screen Shot 2022-10-16 at 20 45 53" src="https://user-images.githubusercontent.com/1512805/196052514-065590a7-3daa-4cce-90a4-f9936b4ad739.png">

If you still can’t get it to work following the steps above, could you post a link to a reproducible example or post the relevant configuration and pages files here? Thanks! :)
