### ISSUE TITLE
Table viewer breaks by scrolling quickly

### ISSUE THREAD

**Issue by kokoroko2** [alephdata/aleph#763] opened 2019-09-18 16:13 UTC
The table viewer breaks by scrolling down at a fast speed. If going down very very slowly, I get to the end of the table.

[CSV for testing with 100k lines](http://eforexcel.com/wp/wp-content/uploads/2017/07/100000-Sales-Records.zip)  
`Example`
![fastscroll2](https://user-images.githubusercontent.com/54646945/65165418-1bf94480-da15-11e9-9671-3222d8ef7474.gif)
`Console msg`
![big-csv](https://user-images.githubusercontent.com/54646945/65165765-c96c5800-da15-11e9-9299-9ae55adacc81.png)

**Comment by pudo** [comment] 2019-11-28 20:33
Have been unable to reproduce in months. Closing until we have a better understanding of the issue.

**Closed by pudo** 2019-11-28 20:33 UTC
