### ISSUE TITLE
When Not Logged, Clicking Link from Email Notification Throws Error

### ISSUE THREAD

**Issue by DavidLemayian** [alephdata/aleph#777] opened 2019-10-07 11:41 UTC
Not necessarily that it shouldn't throw a 403 error but would be useful to add message to prompt user to login:

![image](https://user-images.githubusercontent.com/877919/66308683-59fcd080-e910-11e9-9bb5-cf2887e288e4.png)

**Comment by sunu** [comment] 2019-10-07 12:44
I think it's a more general issue. For example, 404 error pages don't show any error messages either.

**Comment by pudo** [comment] 2019-10-10 16:49
I can't reproduce this. Here's what that screen looks like on my local machine with username/password auth: 

<img width="1207" alt="Screenshot 2019-10-10 at 18 47 46" src="https://user-images.githubusercontent.com/41628/66589283-79a12c80-eb8e-11e9-9be3-d7c2fd3a83e9.png">

In OCCRP production it just redirects to the SSO server. Can you provide more info about what auth mechanism you're using and what language settings might be active?

**Comment by pudo** [comment] 2019-10-10 16:53
Ah, now I understood. Fix is forthcoming.

**Comment by pudo** [comment] 2019-10-10 16:57
Fixed in 347185600026d8f778cd9e33d421a33f74515bf7.

**Closed by pudo** 2019-10-10 16:57 UTC
Labels: ui
