### ISSUE TITLE
Fix and reenable oauth

### ISSUE THREAD

**Issue by thimios** [alephdata/aleph#868] opened 2019-11-18 14:06 UTC
There has been an issue with oauth which has led to oauth being disabled for the moment. 

https://alephdata.slack.com/archives/CE111PS2Y/p1573506198153400?thread_ts=1573466260.146900&cid=CE111PS2Y

@pudo mentioned that it could be an easy fix:

https://alephdata.slack.com/archives/CHTQVUB9U/p1574076378004400

I tried it on a production installation of aleph, version 3.3.6, I have created my key on the google console and I set:

```
ALEPH_OAUTH=true
ALEPH_OAUTH_KEY=XXXXXXXXXXXXXXXXXXXXXXXX
ALEPH_OAUTH_SECRET=XXXXXXXXXXXXXXX
```

But when click on the `login` link on the UI, I get this on the aleph api logs:

```
File "/usr/local/lib/python3.7/dist-packages/authlib/client/oauth_client.py", line 117, in generate_authorize_redirect
api_1               |     raise RuntimeError('Missing "authorize_url" value')
```

**Comment by thimios** [comment] 2019-11-19 13:20
I just tried out https://github.com/alephdata/aleph/pull/869 

I build with `make all`

I have the following aleph.env:

```
# Aleph environment configuration
#
# This file is loaded by docker-compose and transformed into a set of
# environment variables inside the containers. These are, in turn, parsed
# by aleph and used to configure the system.

# Random string:
ALEPH_SECRET_KEY=xxxx

# Visible instance name in the UI
ALEPH_APP_TITLE=Aleph
# Name needs to be a slug, as it is used e.g. for the ES index, SQS queue name:
ALEPH_APP_NAME=aleph
ALEPH_UI_URL=http://localhost:8080/

# ALEPH_URL_SCHEME=https
# ALEPH_FAVICON=https://investigativedashboard.org/static/favicon.ico
# ALEPH_LOGO=http://assets.pudo.org/img/logo_bigger.png

# Other customisations
ALEPH_SAMPLE_SEARCHES=Vladimir Putin:TeliaSonera

# Set email addresses, separated by colons, that will be made admin.
# ALEPH_ADMINS=friedrich@pudo.org:demo@pudo.org

# Login modalities
ALEPH_PASSWORD_LOGIN=false

# OAuth configuration
# Currently supported providers are Google, Facebook and Azure AD OAuth
# Note that you do not need to fill out all fields in order to use it
ALEPH_OAUTH=true
ALEPH_OAUTH_NAME='google'
ALEPH_OAUTH_KEY='xxx.apps.googleusercontent.com'
ALEPH_OAUTH_SECRET='xxx'
ALEPH_OAUTH_SCOPE='openid email profile'
ALEPH_OAUTH_BASE_URL='https://www.googleapis.com/oauth2/v2/'
ALEPH_OAUTH_TOKEN_URL='https://www.googleapis.com/oauth2/v4/token'
ALEPH_OAUTH_AUTHORIZE_URL='https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent'

# Where and how to store the underlying files:
# ARCHIVE_TYPE=file
# ARCHIVE_PATH=/data
# Or, if 'ALEPH_ARCHIVE_TYPE' configuration is 's3':
# ARCHIVE_BUCKET=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=

# Queue mechanism
# REDIS_URL=redis://redis:6379/0

# Content options
ALEPH_OCR_DEFAULTS=en
# ALEPH_LANGUAGES=en:de:fr:es:tr:ar ...

# Provide a valid email to send alerts from:
ALEPH_MAIL_FROM=
ALEPH_MAIL_HOST=
ALEPH_MAIL_ADMIN=
ALEPH_MAIL_USERNAME=
ALEPH_MAIL_PASSWORD=
ALEPH_MAIL_PORT=25
ALEPH_MAIL_USE_TLS=false

# Debug mode (insecure)
ALEPH_DEBUG=false

# Read-only mode:
# ALEPH_MAINTENANCE=true

# Enable HTTP caching
# ALEPH_CACHE=true

```
This is my client id configuration on the google cloud:

![client_id](https://user-images.githubusercontent.com/153234/69149563-6ebbaf00-0adf-11ea-92a6-f135364f4369.png)


I am getting the following on the docker logs:
```
Attaching to aleph_api_1, aleph_ui_1
ui_1                |
ui_1                | > aleph-ui@3.3.6 start /alephui
ui_1                | > node scripts/start.js
ui_1                |
ui_1                | ℹ ｢wds｣: Project is running at http://172.23.0.8/
ui_1                | ℹ ｢wds｣: webpack output is served from /
ui_1                | ℹ ｢wds｣: Content not from webpack is served from /alephui/public
ui_1                | ℹ ｢wds｣: 404s will fallback to /index.html
ui_1                | Starting the development server...
ui_1                |
api_1               |  * Environment: production
api_1               |    WARNING: This is a development server. Do not use it in a production deployment.
api_1               |    Use a production WSGI server instead.
api_1               |  * Debug mode: off
api_1               | INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ui_1                | Compiled with warnings.
ui_1                |
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                |
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                |
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                |
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                |
ui_1                | Search for the keywords to learn more about each warning.
ui_1                | To ignore, add // eslint-disable-next-line to the line before.
ui_1                |
api_1               | DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254
api_1               | INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 1 of 3
api_1               | DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254
api_1               | INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 2 of 3
api_1               | DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254
api_1               | INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 3 of 3
api_1               | DEBUG:aleph.core:Disable Stackdriver: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentic
ation/getting-started
api_1               | INFO:werkzeug:172.23.0.8 - - [19/Nov/2019 13:00:40] "GET /api/2/metadata HTTP/1.1" 200 -
api_1               | DEBUG:aleph.authz:[C] Authz: <Authz(None)> (read): [1]
api_1               | INFO:werkzeug:172.23.0.8 - - [19/Nov/2019 13:00:40] "GET /api/2/statistics HTTP/1.1" 200 -
api_1               | INFO:werkzeug:172.23.0.8 - - [19/Nov/2019 13:00:52] "GET /api/2/metadata HTTP/1.1" 200 -
api_1               | INFO:werkzeug:172.23.0.8 - - [19/Nov/2019 13:02:04] "GET /api/2/metadata HTTP/1.1" 200 -
api_1               | DEBUG:aleph.authz:[C] Authz: <Authz(None)> (read): [1]
api_1               | INFO:werkzeug:172.23.0.8 - - [19/Nov/2019 13:02:05] "GET /api/2/statistics HTTP/1.1" 200 -
api_1               | INFO:werkzeug:172.23.0.8 - - [19/Nov/2019 13:02:11] "GET /api/2/metadata HTTP/1.1" 200 -
api_1               | DEBUG:aleph.authz:[C] Authz: <Authz(None)> (read): [1]

```

This is what I see on my browser:

![Screenshot from 2019-11-19 15-19-04](https://user-images.githubusercontent.com/153234/69149860-120cc400-0ae0-11ea-9de6-e8873fd01132.png)

@sunu I guess I am configuring something wrong?

**Comment by pudo** [comment] 2019-11-20 11:37
I think this just a misconfiguration of the React proxy in the development config. If you replace `localhost:8080` for `localhost:5000` for those direct API calls it should not give that UI error.

**Comment by thimios** [comment] 2019-11-20 12:17
@pudo I am not sure how I can fix the misconfiguration of the React proxy. Is it the "Authorized redirect URIs" in the Client ID for Web Application configuration screen on the Google Cloud Console, or maybe the ALEPH_UI_URL in the env file?

If you think that it is not easy to test this PR in development mode and the best would be to just merge it in and release a new version, please go ahead, I just wanted to help by testing.

**Comment by pudo** [comment] 2019-11-20 13:30
@thimios I don't know how to fix the react proxy, either. If you figure it out please let me know. But the problem is just that React doesn't forward direct browser access to the backend, so instead of doing the OAuth flow it just shows a random frontend error.

**Comment by thimios** [comment] 2019-11-20 18:18
@pudo do you think that this is a problem that appears only on the development env and will not happen on production?

**Comment by pudo** [comment] 2019-11-21 08:24
Yep, it's about how we access the JS assets in development. @kjacks do you think you could look into how to configure the react http proxy properly so that *anything* going to `/api` is *always* handled by the backend, and never by the front-end?

**Comment by thimios** [comment] 2019-11-25 11:00
@sunu I am testing with a fresh production installation of 3.3.8, this is my aleph.env:

**Comment by thimios** [comment] 2019-11-25 11:10
@sunu I am testing with a fresh production installation of 3.3.8, this is my aleph.env:

```
# Random string:
ALEPH_SECRET_KEY=xxxx
# Visible instance name in the UI
ALEPH_APP_TITLE=Aleph
# Name needs to be a slug, as it is used e.g. for the ES index, SQS queue name:
ALEPH_APP_NAME=aleph
ALEPH_UI_URL=https://sanctions.xxx.com/
ALEPH_URL_SCHEME=https
# ALEPH_FAVICON=https://investigativedashboard.org/static/favicon.ico
# ALEPH_LOGO=http://assets.pudo.org/img/logo_bigger.png
# Other customisations
ALEPH_SAMPLE_SEARCHES=Vladimir Putin:TeliaSonera
# Set email addresses, separated by colons, that will be made admin.
ALEPH_ADMINS=thimios@xxx.com, alex@xxxxx.com
# Login modalities
ALEPH_PASSWORD_LOGIN=false
# OAuth configuration
# Currently supported providers are Google, Facebook and Azure AD OAuth
# Note that you do not need to fill out all fields in order to use it
ALEPH_OAUTH=true
ALEPH_OAUTH_NAME='google'
ALEPH_OAUTH_KEY='218518xxxxxx.apps.googleusercontent.com'
ALEPH_OAUTH_SECRET='u4EqDnMFexxxxxxxxxxxxxxx'
ALEPH_OAUTH_SCOPE='openid email profile'
ALEPH_OAUTH_BASE_URL='https://www.googleapis.com/oauth2/v2/'
ALEPH_OAUTH_TOKEN_URL='https://www.googleapis.com/oauth2/v4/token'
ALEPH_OAUTH_AUTHORIZE_URL='https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent'
# Where and how to store the underlying files:
# ARCHIVE_TYPE=file
# ARCHIVE_PATH=/data
# Or, if 'ALEPH_ARCHIVE_TYPE' configuration is 's3':
# ARCHIVE_BUCKET=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# Queue mechanism
# REDIS_URL=redis://redis:6379/0
# Content options
ALEPH_OCR_DEFAULTS=en
# ALEPH_LANGUAGES=en:de:fr:es:tr:ar ...
# Provide a valid email to send alerts from:
ALEPH_MAIL_FROM=noreply@sanctions.xxx.com
ALEPH_MAIL_HOST=smtp.xxx.net
ALEPH_MAIL_ADMIN=ak@xxxxx.com
ALEPH_MAIL_USERNAME=apikey
ALEPH_MAIL_PASSWORD=SG.VTrUxxxxxxxxxxxE
ALEPH_MAIL_PORT=587
ALEPH_MAIL_USE_TLS=true
# Debug mode (insecure)
ALEPH_DEBUG=true
# Read-only mode:
# ALEPH_MAINTENANCE=true
# Enable HTTP caching
# ALEPH_CACHE=true
```
The home page of the aleph UI opens on my browser and when I hit the login link on the top right, I get redirected to the URL:

```
http://sanctions.givve.com/api/2/sessions/'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent%27&response_type=code&client_id=%27218518715999-8unualvm7ff82doea4s84nhn1ud1p5p5.apps.googleusercontent.com%27&redirect_uri=https%3A%2F%2Fsanctions.givve.com%2Fapi%2F2%2Fsessions%2Fcallback&scope=%27openid+email+profile%27&state=%2F
```

which is timing out... I am not getting any other errors either on the server side or the browser console. I tried commenting out the `ALEPH_OAUTH_AUTHORIZE_URL` but then I get a server error complaining that the authorize url is not set.

@sunu I tried to follow the configuration you mentioned on: https://github.com/alephdata/aleph/pull/869 but I guess I am doing something wrong. Would you have any hints?

**Comment by pudo** [comment] 2019-11-25 11:36
Did you try removing the quotes in your `aleph.env`?

**Comment by pudo** [comment] 2019-11-26 08:29
I'm interpreting your "thumbs up" to mean that worked, and closing this ticket. Please re-open if there is an issue with Google OAuth.

**Closed by pudo** 2019-11-26 08:29 UTC

**Comment by thimios** [comment] 2019-11-26 08:56
thanks @pudo just for documentation purposes, this is the configuration that finally worked for me:

```
ALEPH_OAUTH=true                                                                                                                                                                                                                                      
ALEPH_OAUTH_NAME=google                                                                                                                                                                                                                               
ALEPH_OAUTH_KEY=xxxxxx.apps.googleusercontent.com                                                                                                                                                              
ALEPH_OAUTH_SECRET=xxxxxxxxxxxxxx                                                                                                                                                                                                           
ALEPH_OAUTH_SCOPE=openid email profile                                                                                                                                                                                                                
ALEPH_OAUTH_BASE_URL=https://www.googleapis.com/oauth2/v2/                                                                                                                                                                                            
ALEPH_OAUTH_TOKEN_URL=https://www.googleapis.com/oauth2/v4/token                                                                                                                                                                                      
ALEPH_OAUTH_AUTHORIZE_URL=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent      
```
