### ISSUE TITLE
symlink ui/src/node_modules/src breaks dev build

### ISSUE THREAD

**Issue by jbothma** [alephdata/aleph#348] opened 2018-03-10 09:39 UTC
```bash
docker-compose -f docker-compose.dev.yml  build ui
Building ui
ERROR: Error processing tar file(exit status 1): symlink .. /src/node_modules/src/node_modules/src: no such file or directory
```

**Comment by iaincollins** [comment] 2018-03-10 16:47
Just to confirm the cause of this issue, can I ask what OS you are using on your local system?

I'm assuming it's Windows as the following steps should work on Unix:

    git clone https://github.com/alephdata/aleph.git
    cd aleph
    cp aleph.env.tmpl aleph.env
    docker-compose -f docker-compose.dev.yml  build ui

If you are not running Windows, it would helpful if you can confirm your OS, tar version and your file system - and steps to replicate.

I'd like to refactor the Aleph UI to not use a symlink but am going to follow up with that in a seperate comment below.

**Comment by jbothma** [comment] 2018-03-10 16:52
Sorry I gave very little info. I'm on linux. This was the master branch cloned this morning, I think.

Deleting the symlink allowed `make build` to finish, but `make web` obviously didn't work because the assets weren't available.

I first suspected I screwed things up by cleaning up my docker installation a bit yesterday. I'll try to reproduce with a fresh clone with  different docker-compose base named

**Comment by iaincollins** [comment] 2018-03-10 17:08
I think a fresh clone is a good idea for now. It should work, but it currently uses a symlink which is nasty and will cause problems on some operating systems (and on some file systems, even on Unix) and we should move away from doing using one. Will follow this up.

**Comment by jbothma** [comment] 2018-03-10 17:15
Nope, look like this fails for me in a fresh clone. 

```
$ git clone https://github.com/alephdata/aleph.git aleph-build-test
Cloning into 'aleph-build-test'...
remote: Counting objects: 29495, done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 29495 (delta 78), reused 88 (delta 48), pack-reused 29346
Receiving objects: 100% (29495/29495), 8.79 MiB | 175.00 KiB/s, done.
Resolving deltas: 100% (22476/22476), done.
```
```
 $ cd aleph-build-test/
```
```
 (master) $ cp aleph.env.tmpl aleph.env
```
```
make all
docker-compose -f docker-compose.dev.yml  build
postgres uses an image, skipping
elasticsearch uses an image, skipping
...
Successfully tagged alephbuildtest_api:latest
Building ui
ERROR: Error processing tar file(exit status 1): symlink .. /src/node_modules/src/node_modules/src: no such file or directory
make: *** [Makefile:41: build] Error 1
```

**Comment by iaincollins** [comment] 2018-03-10 17:16
Ugh! Thanks for confirming!

**Comment by iaincollins** [comment] 2018-03-10 19:11
Okies, I have what I think is a fix for this (refactoring the UI to not use a symlink as way to load libraries) and it seems to be fine here and can be done without totally breaking things like IDE auto-complete, but I need to chat to the core team working on the UI on Monday (@pudo, @emmina) about it to see if they are okay with it - and to go over the other options if they don't.

I'd post it here but it's kind of long, complex and full of caveats - and I'm having trouble with my local Docker to check for potential issues (it is is having problems and currently spewing out random mangled unicode at me), so I need to resolve that now. 💻🔥

Will post an update after I've talked to folks on Monday.

**Comment by iaincollins** [comment] 2018-03-10 19:28
BTW, it would be interesting to know the output of `df -Th` on your system, just for the record.

e.g. 

    $ df -Th
    Filesystem     Type      Size  Used Avail Use% Mounted on
    udev           devtmpfs  492M   12K  492M   1% /dev
    tmpfs          tmpfs     100M  368K   99M   1% /run
    /dev/xvda1     ext4      7.8G  4.8G  2.6G  65% /

**Comment by jbothma** [comment] 2018-03-11 06:30
```
Filesystem                  Size  Used Avail Use% Mounted on
dev                         3.9G     0  3.9G   0% /dev
run                         3.9G  1.6M  3.9G   1% /run
/dev/mapper/MyStorage-root   25G   16G  8.2G  66% /
tmpfs                       3.9G  299M  3.6G   8% /dev/shm
tmpfs                       3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs                       3.9G  216K  3.9G   1% /tmp
/dev/sda1                   511M  106M  406M  21% /boot
/dev/mapper/MyStorage-home  201G  169G   22G  89% /home
tmpfs                       789M   20K  789M   1% /run/user/1000
```

**Comment by iaincollins** [comment] 2018-03-11 12:47
Thanks @jbothma 

That doesn't look like output of `df -Th` (at least with GNU coreutils) and it doesn't say the file system type (which is the relevant bit here it for us). Would be great to know that and the distro you are using.

Could you confirm? Thanks!

    $ uname -a
    Linux ip-172-31-59-7 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015     x86_64 x86_64 x86_64 GNU/Linux
    $ df --version
    df (GNU coreutils) 8.21
    $ df -T
    Filesystem     Type     1K-blocks    Used Available Use% Mounted on
    udev           devtmpfs    503212      12    503200   1% /dev
    tmpfs          tmpfs       101636     364    101272   1% /run
    /dev/xvda1     ext4       8115168 4989720   2690172  65% /

**Comment by jbothma** [comment] 2018-03-11 13:06
oh dear, sorry - didn't pay attention
```
Linux robin 4.14.24-1-lts #1 SMP Tue Mar 6 17:05:53 CET 2018 x86_64 GNU/Linux
```
```
Filesystem                 Type      Size  Used Avail Use% Mounted on
dev                        devtmpfs  3.9G     0  3.9G   0% /dev
run                        tmpfs     3.9G  1.6M  3.9G   1% /run
/dev/mapper/MyStorage-root ext4       25G   16G  8.2G  66% /
tmpfs                      tmpfs     3.9G  290M  3.6G   8% /dev/shm
tmpfs                      tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs                      tmpfs     3.9G  1.1M  3.9G   1% /tmp
/dev/sda1                  vfat      511M  106M  406M  21% /boot
/dev/mapper/MyStorage-home ext4      201G  170G   21G  90% /home
tmpfs                      tmpfs     789M   20K  789M   1% /run/user/1000
```

**Comment by jbothma** [comment] 2018-03-11 13:07
This isn't a big issue for me though - I finally got the stable branch running - so you can close this since you're removing the link anyway.

**Comment by iaincollins** [comment] 2018-03-11 13:17
Thanks, thanks super helpful!

It's puzzling as would expect it to work given that output, but it's very good to know to understand the impact (i.e. your setup doesn't look unusual, which lends more justification to us spending time addressing it).

**Comment by jbothma** [comment] 2018-03-12 21:11
Sadly your branch gives me 
```
i_1             | Wrote 41 CSS files to /alephui/src/
ui_1             | Compiling...
ui_1             | Failed to compile.
ui_1             | 
ui_1             | ./src/index.js
ui_1             | Module not found: Can't resolve 'app/App' in '/alephui/src'
```
on `make web`

**Comment by jbothma** [comment] 2018-03-12 21:12
```
 (master) $ docker version
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.4
 Git commit:	fc4de447b5
 Built:	Tue Feb 13 15:28:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	fc4de447b5
  Built:	Tue Feb 13 15:28:34 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

I'm running arch, so probably my fualt :D

**Comment by jbothma** [comment] 2018-03-12 22:01
I see you've got a ui build in docker hub - that'll do fine for me - I'm on master and it's (almost) running yay!

I also created my own build which succeeded - so there's proof that it really builds :D

**Closed** 2018-03-17 11:33 UTC
Labels: bug, ui
