### ISSUE TITLE
FEATURE:  Document content preview directly in search output window

### ISSUE THREAD

**Issue by AndreaPux** [alephdata/aleph#2956] opened 2023-03-24 10:41 UTC
**Is your feature request related to a problem? Please describe.**
Aleph is great for searching the content of large number of pdf file, but the way the results are listed and shown could be better. 

**Describe the solution you'd like**
1) When I search for given text in the documents, I would love to see a preview of the content directly in the file listing window, showing the first occurrence of the target words and the surrounding text. 

2) Moreover, when I click on a given document, the preview window should not open on the first page, but on the page(s) where the text occurs, possibily highlighting the target words. Currently the PDF preview is not useful, it opens a file which can be 500 pages , I know the text is somewhere there, but no way to find it other than dowloading the file and opening locally in a viewer.

Thanks,

**Comment by tillprochaska** [comment] 2023-03-24 11:28
Hi @AndreaPux, thanks for the feedback!

Regarding 1) This has been a known issue (#2138) for some time, but unfortunately, we haven’t been able to release a fix yet. Thanks for bringing this up again though!

Regarding 2) I think this is a duplicate of #1925. While this issue has also been open for quite a while, I have good news: We will likely spend some time to improve the overall search UX later this year.

In the meantime, here is a workaround that isn’t optimal, but can help you navigate long documents. When you expand the search result (clicking the button in the top left corner of the overlay), you can search within the document and can then navigate to pages containing your search query.

As there are already issues tracking the two feature requests you raised, I will close this issue. Feel free to subscribe to the linked issues to get notifications when there’s progress.

In case the linked issues are actually different from what you want, please feel free to reopen the issue! Thanks!

**Closed by tillprochaska** 2023-03-24 11:28 UTC
Labels: feature-request, triage
